pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: docker
                image: docker:27.2.0-alpine3.20
                command:
                - cat
                tty: true
                volumeMounts:
                - name: docker-socket
                  mountPath: "/var/run/docker.sock"
              - name: kubectl
                image: gcr.io/cloud-builders/kubectl
                command:
                - cat
                tty: true
              volumes:
              - name: docker-socket
                hostPath:
                  path: "/var/run/docker.sock"
            '''
        }
    }

    tools {
        nodejs 'NodeJS 22.8.0'
    }

    environment {
        DOCKER_HUB_REPO = 'henhen7/be08-4th-2team' // -> ${도커허브 아이디}/{레포지토리 이름}
        DOCKER_IMAGE_TAG = "1.${env.BUILD_NUMBER}-fe" // Jenkins에서 자동으로 생성
    }
    stages {
        // GitHub에서 소스 코드 체크아웃
        stage('Checkout Code from GitHub') {
            steps {
                git branch: 'jenkins-back',
                url: 'https://github.com/beyond-sw-camp/be08-4th-2team.git',
                credentialsId: 'be08-4th-2team-jenkins'
            }
        }

        stage('Check Changes') {
            steps {
                script {
                    // 변경된 파일 목록 가져오기
                    def changedFiles = sh(script: 'git diff-tree --no-commit-id --name-only -r $GIT_COMMIT', returnStdout: true).trim().split('\n')

                    // 프론트엔드 디렉터리 변경 감지
                    env.FRONTEND_CHANGED = changedFiles.any { it.startsWith('frontend/') } ? 'true' : 'false'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') {
                    sh "npm install"
                }
            }
        }
        stage('Build Frontend') {
            when {
                expression { env.FRONTEND_CHANGED == 'true' }
            }
            steps {
                dir('frontend') {
                    sh "npm run build"
                }
            }
        }
        stage('Docker Image Build & Push') {
            when {
                expression { env.FRONTEND_CHANGED == 'true' }
            }
            steps {
                container('docker'){
                    dir('frontend') {
                        script {
                            echo "DOCKER_IMAGE_TAG: $DOCKER_IMAGE_TAG"
                            sh 'docker logout'

                            withCredentials([usernamePassword(credentialsId: 'dockerhub_access', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD' )]) {
                                sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'
                            }

                            sh 'docker build --no-cache -t $DOCKER_HUB_REPO:$DOCKER_IMAGE_TAG ./'
                            sh 'docker image inspect $DOCKER_HUB_REPO:$DOCKER_IMAGE_TAG'
                            sh 'docker push $DOCKER_HUB_REPO:$DOCKER_IMAGE_TAG'

                            sh 'docker logout'
                        }
                    }
                }
            }
        }
        // Deployment
        stage('Deployment') {
            steps {
                container('kubectl') {
                    script() {
                        def isDeploy = input(
                            id: 'deploy',
                            message: '배포하시겠습니까?',
                            parameters: [
                                [$class: 'BooleanParameterDefinition', defaultValue: false, description: '', name: '배포를 하려면 체크해 주세요.']
                            ]
                        )

                        if (isDeploy) {
                            def dockerImageTag = "${env.BUILD_NUMBER}"
                            echo "DockerImageTag : ${dockerImageTag}"
                            sh '/builder/kubectl version'
                            sh '/builder/kubectl get po'
//                             sh 'kubectl set image deploy department-deploy department=$DOCKER_HUB_REPO:$DOCKER_IMAGE_TAG -n default'
                        }
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Frontend application successfully built and Docker image pushed!'
        }
        failure {
            echo 'Failed to build or push Docker image.'
        }
    }
}
