apiVersion: apps/v1 
kind: Deployment 

metadata: 
  name: backend-deployment 

spec: 
  replicas: 2
  strategy: 
    type: RollingUpdate 
  revisionHistoryLimit: 1 
  minReadySeconds: 10 
  selector: 
    matchLabels: 
      type: backend 
  template: 
    metadata:
      labels: 
        type: backend 
    spec: 
      containers: 
        - name: backend-container 
          image: henhen7/be08-4th-2team:1.0-be 
          resources: 
            requests: 
              memory: "1024Mi"
              cpu: "600m"
            limits: 
              memory: "3Gi" 
              cpu: "2000m" 
          ports:
          - containerPort: 8080
      terminationGracePeriodSeconds: 5
