apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: frontend-deployment 
spec: 
  replicas: 2 
  strategy: 
    type: RollingUpdate 
  revisionHistoryLimit: 1 
  selector: 
    matchLabels: 
      type: frontend 
  template: 
    metadata: 
      labels: 
        type: frontend 
    spec: 
      containers: 
        - name: frontend-container 
          image: henhen7/be08-4th-2team:1.0-fe 
          resources: 
            requests: 
              memory: "1024" 
              cpu: "600m" 
            limits: 
              memory: "3Gi" 
              cpu: "2000m" 
          readinessProbe: 
            httpGet: 
              path: / 
              port: 80 
            initialDelaySeconds: 20 
            periodSeconds: 10 
            successThreshold: 3 
          livenessProbe: 
            httpGet: 
              path: / 
              port: 80 
            initialDelaySeconds: 20 
            periodSeconds: 10 
